### ISSUE TITLE
Discussion: Backend design

### ISSUE THREAD

**Issue by lfb0801** [Tournamanager/api#1]
There are multiple frameworks and languages to make the backend in. Personaly I believe Spring with Java or Kotlin would be the issiest to set up. Any other opinions?

**Comment by MindHawk** [comment]
Java is explicitly mentioned in the blokboek and is (should be) very familiar to everyone in the project, so it has my preference. Spring is probably fine, though I've not worked with it personally (yet)

**Comment by lfb0801** [comment]
Teachers have explained that Java isn't mandatory, but using it is fine for me.
### Talking about the framework,
The use of spring allows for autogenerative bean creation and maintenance. 
when using spring, thinking ahead about which dependencies we'll need is a really important step. 
Personally I would suggest using spring-webflux in stead of spring-web : Which would allow for more functional programming.
### For the database: 
MySql is supported by te school, but requires Anyconnect to be open, which is not ideal.

**Comment by MindHawk** [comment]
**Framework**
Spring seems fine to me, I'll learn how to use it.

**Database**
Anyconnect is super annoying, but using an Azure database is also pretty annoying. Are there any other (free) alternatives?
