### ISSUE TITLE
Cannot add a user to multiple teams

### ISSUE THREAD

**Issue by chf3kl9** [Tournamanager/api#135]
**Describe the bug**
When trying to add a user to a team while the user already is in a team, you get an internal server error (500).

![image](https://user-images.githubusercontent.com/17722335/70913954-5031d080-2017-11ea-936f-444b01840002.png)
![image](https://user-images.githubusercontent.com/17722335/70913978-5b84fc00-2017-11ea-823c-363d1e5107c5.png)
![image](https://user-images.githubusercontent.com/17722335/70913996-6475cd80-2017-11ea-9b85-8a5da70a364a.png)
![image](https://user-images.githubusercontent.com/17722335/70914009-6cce0880-2017-11ea-8e57-01f336053f73.png)

**Expected behavior**
The user should be added to the new team.

**Comment by lfb0801** [comment]
@chf3kl9 @ManyToMany relation much?
