### ISSUE TITLE
Get all users

### ISSUE THREAD

**Issue by larsvandriel** [Tournamanager/api#51]
What has to be done:
Get a list of all users from the database.

Why it has to be done:
So that the users can view all the other users that have been created.

When the task is done:
The frontend application can call the backend application to get all the users. The frontend can pass filter or search parameters with the request so that the user can search the exact user they want. The backend should also be compatible with the pagination at the frontend.

**Comment by MindHawk** [comment]
Solution was not sufficient for the issue.

**Comment by MindHawk** [comment]
Nevermind.
