### ISSUE TITLE
Update account

### ISSUE THREAD

**Issue by larsvandriel** [Tournamanager/api#59]
What has to be done:
Edit an account and update the account in database

Why it has to be done:
So that the user can update his account, so that the account has the correct information.

When the task is done:
The frontend application can call the backend application with all information to edit an account.
When the account info, was invalid it must return an error.
When the account info, settings were valid, it updates the record in the database.

**Comment by chf3kl9** [comment]
After some discussion, we will delete this, as it has no uses and can only be misused.
Closing Task
